spring.application.name=weather-forecast-service

spring.mvc.problemdetails.enabled=true

metno.base-url=https://api.met.no
metno.user-agent=weather-forecast-service github.com/Sureac/weather-forecast-service
metno.connect-timeout=2s
metno.read-timeout=5s
